apiVersion: v1
kind: Template
metadata:
  name: os-demo
  annotations:
    description: "Matt Mahoney - OS Demo" 
    iconClass: "icon-git" 
    tags: "openshift" 
objects:   
- apiVersion: v1
  kind: Pod
  metadata:
    name: os-demo
  spec:
    containers:
    - env:
      - name: OS-DEMO
      image: mattmahoneyrh/hello-world
      name: master
      ports:
      - containerPort: 8000
        protocol: TCP
parameters:  
labels:      
  redis: os-demo


